### PR TITLE
add feature flush_only

### PR DESCRIPTION
**Pull request by thuhak**
# Feature needed

In some cases, I need to flush cache periodically.

### CODE REVIEW

**Comment by taylorhakes** [comment]
@thuhak Can you explain this feature more? How is the `invalidate()` function different?

**Comment by thuhak** [comment]
In my scenario,  I need to update the cache directly, modify them rather than delete and add. because it's not transaction actually. Something may happen between the 2 operations.

The use case is just like the code as below:

```python
@cache(namespace='abc')
def get_item(key):
     item_info = slow_get(key)
     return item_info

items = dict()    #global dict

@cache(namespace='abc', flush_only=True)
def update_cache(key):
    return keys.get(key)

get_all_items()   #get all values in one function, then flush them to the cache to make the cache fresh. 
for i in items:
     update_cache(i)
```

I will be glad to follow your design if there is better way to do that

**Comment by taylorhakes** [comment]
@thuhak Thanks for explaining. I think I understand your use case now. I would recommend we add a new function to update the cache instead like the following `.update_cache(value, args=None, kwargs=None)`

In your case you would write the following.

```python
@cache(namespace='abc')
def get_item(key):
     item_info = slow_get(key)
     return item_info

items = dict()    #global dict

get_all_items()   #get all values in one function, then flush them to the cache to make the cache fresh. 
for i in items:
     get_item.update_cache(keys.get(key), args=[i])
```

Does that work for your use case?

**Comment by thuhak** [comment]
> @thuhak Thanks for explaining. I think I understand your use case now. I would recommend we add a new function to update the cache instead like the following `.update_cache(value, args=None, kwargs=None)`
> 
> In your case you would write the following.
> 
> ```python
> @cache(namespace='abc')
> def get_item(key):
>      item_info = slow_get(key)
>      return item_info
> 
> items = dict()    #global dict
> 
> get_all_items()   #get all values in one function, then flush them to the cache to make the cache fresh. 
> for i in items:
>      get_item.update_cache(keys.get(key), args=[i])
> ```
> 
> Does that work for your use case?

That sounds good

**Pull request closed without merging**
